apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: app
data:
  KEYCLOAK_ISSUER_URI: "http://keycloak.localhost:8090/realms/payments"
  TRANSACTION_SERVICE_URL: "http://transaction-service.app.svc.cluster.local:8080"
  REDIS_HOST: "redis-master.data.svc.cluster.local"
  REDIS_PORT: "6379"
