apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: app
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: micro/api-gateway:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
            - containerPort: 5005
              name: jdwp
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=50 -XX:InitialRAMPercentage=25 -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Dspring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak.auth.svc.cluster.local/realms/payments/protocol/openid-connect/certs"
            - name: KEYCLOAK_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: KEYCLOAK_ISSUER_URI
            - name: TRANSACTION_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: TRANSACTION_SERVICE_URL
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: REDIS_PORT
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 384Mi
            limits:
              cpu: 1000m
              memory: 512Mi
